// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoHpZJDyQGBzDpo3kCiWETJodsbfBMbH4',
    appId: '1:766479092387:web:46f0d8569858d8982f0d16',
    messagingSenderId: '766479092387',
    projectId: 'recipes-252f1',
    authDomain: 'recipes-252f1.firebaseapp.com',
    storageBucket: 'recipes-252f1.appspot.com',
    measurementId: 'G-GKZ39SM6TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-uLagoMVpAEygicRC_Mk6sa0vnpKzzhE',
    appId: '1:766479092387:android:26895cf244160e632f0d16',
    messagingSenderId: '766479092387',
    projectId: 'recipes-252f1',
    storageBucket: 'recipes-252f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXy1Zxc67-OwMxinpF5uLVeKWypWuD-_w',
    appId: '1:766479092387:ios:39bfd11c9ce8add12f0d16',
    messagingSenderId: '766479092387',
    projectId: 'recipes-252f1',
    storageBucket: 'recipes-252f1.appspot.com',
    iosBundleId: 'com.arandas.recipeApp',
  );
}
